name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Clean npm cache
        run: npm cache clean --force
      - name: Install dependencies
        run: npm install
      - name: List installed packages
        run: npm list --depth=0
      - name: Run linter
        run: npx eslint .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm test -- --coverage
      - name: Download CodeClimate reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
      - name: Format coverage
        run: ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json ./coverage/lcov.info
      - name: Upload coverage to CodeClimate
        run: ./cc-test-reporter upload-coverage
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
